apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: service-catalog
spec:
  rules:
  - host: catalog.localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-catalog
            port:
              number: 80
